spring:
  application:
    name: "ecommerceapi"

  datasource:
    url: "jdbc:mysql://localhost:3306/full-stack-ecommerce"
    username: "ecommerceapp"
    password: "ecommerceapp"
    driver-class-name: "com.mysql.cj.jdbc.Driver"

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate

logging:
  level:
    nyclab:
      ecommerce:
        ecommerceapi: Debug

allowed:
  origin: "http://localhost:4200"